;; (add-to-list 'auto-mode-alist '("\\.ts$" . javascript-mode))
;; (add-to-list 'auto-mode-alist '("\\.tsx$" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.ts$" . js-mode))
(add-to-list 'auto-mode-alist '("\\.tsx$" . js-jsx-mode))
(setq indent-tabs-mode nil)
(setq js-indent-level 4)
